name: Export TimeTree Calendar

on:
  schedule:
    - cron: '0 */6 * * *'  # 每天執行
  workflow_dispatch:      # 允許手動觸發

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: |
          sudo apt-get install -y expect
          python -m pip install --upgrade pip
          pip install -e .
          
      - name: Create expect script
        run: |
          cat > export.exp << 'EOF'
          #!/usr/bin/expect -f
          set email [lindex $argv 0]
          set password [lindex $argv 1]
          
          spawn python -m timetree_exporter -e "$email" -o calendar.ics
          expect "password:"
          send "$password\r"
          expect "export?"
          send "4\r"
          expect eof
          EOF
          chmod +x export.exp
          
      - name: Export Calendar
        env:
          TIMETREE_EMAIL: ${{ secrets.TIMETREE_EMAIL }}
          TIMETREE_PASSWORD: ${{ secrets.TIMETREE_PASSWORD }}
        run: |
          ./export.exp "$TIMETREE_EMAIL" "$TIMETREE_PASSWORD"
          
      - name: Upload calendar file
        uses: actions/upload-artifact@v4
        with:
          name: calendar
          path: calendar.ics
          retention-days: 1
