# 在 repository 建立 .github/workflows/export.yml
name: Export TimeTree Calendar

on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小時執行
  workflow_dispatch:        # 允許手動觸發

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          
      - name: Install dependencies
        run: |
          pip install selenium
          pip install -r requirements.txt
          
      - name: Run exporter
        env:
          EMAIL: ${{ secrets.TIMETREE_EMAIL }}
          PASSWORD: ${{ secrets.TIMETREE_PASSWORD }}
          CALENDAR_ID: ${{ secrets.TIMETREE_CALENDAR_ID }}
        run: python main.py
        
      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add calendar.ics
          git commit -m "Update calendar $(date '+%Y-%m-%d %H:%M:%S')" || exit 0
          git push
