name: TimeTree Export

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  export:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 重要，寫入權限
      pages: write #寫入 pages
      id-token: write # 權限

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y expect curl
          python -m pip install --upgrade pip
          pip install -e .


      - name: Run TimeTree Exporter (with Expect)
        run: |
          expect << EOF
          set timeout -1
          spawn python -m timetree_exporter -e "${{ secrets.TIMETREE_EMAIL }}" -o calendar.ics
          expect "Enter your password:"
          send "${{ secrets.TIMETREE_PASSWORD }}\r"
          expect "Which Calendar do you want to export? (Default to 1):"
          send "4\r"
          expect eof
          EOF
       

      - name: Update Home Assistant Calendar (via API)
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.HA_LONG_LIVED_TOKEN }}" \
               -H "Content-Type: text/calendar" \
               -d @calendar.ics \
               "${{ secrets.HA_EXTERNAL_URL }}/api/calendars/calendar.ics"  # 修改這裡
        env:
            HA_EXTERNAL_URL: ${{ secrets.HA_EXTERNAL_URL }}
