name: TimeTree Export

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  export:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          sudo apt-get install -y expect
          pip install -r requirements.txt
          pip install selenium==4.17.2

      - name: Download latest chromedriver #下載最新
        run: |
          LATEST_CHROMEDRIVER_VERSION=$(curl -s https://googlechromelabs.github.io/chrome-for-testing/LATEST_RELEASE_STABLE)
          wget -O /tmp/chromedriver.zip https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/${LATEST_CHROMEDRIVER_VERSION}/linux64/chromedriver-linux64.zip
          unzip /tmp/chromedriver.zip -d /usr/local/bin/

      - name: Run TimeTree Exporter (with Expect)
        run: |
          export CALENDAR_ID=${{ secrets.TIMETREE_CALENDAR_ID }} #在這邊設定好
          cat << EOF | python -m timetree_exporter -e ${{ secrets.TIMETREE_EMAIL }} -o calendar.ics
          ${{ secrets.TIMETREE_PASSWORD }}
          EOF

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: timetree-calendar
          path: calendar.ics
